[phases]
build = "composer install --optimize-autoloader --no-dev && php artisan key:generate && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force"

install = "npm install && npm run build"

start = "php artisan serve --host=0.0.0.0 --port=$PORT"
